apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservicio-java-deployment
  labels:
    app: microservicio-java
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microservicio-java
  template:
    metadata:
      labels:
        app: microservicio-java
    spec:
      type: LoadBalancer
      containers:
      - name: microservicio-java
        image: mfigueroah/microservicio-java:latest
        ports:
        #- containerPort: 8080
          - port: 80
          - targetPort: 8080
          name: http
